version: '3.8'
services:
  vector-cloud:
    build: .
    container_name: vector-alice-cloud
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DB_USER=yerniyaz
      - DB_PASSWORD=vector_secret
      - DB_NAME=vector_db
      - DB_HOST=db
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    container_name: vector-db
    restart: always
    environment:
      - POSTGRES_USER=yerniyaz
      - POSTGRES_PASSWORD=vector_secret
      - POSTGRES_DB=vector_db
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data