version: '3.8'
services:
  vector-cloud:
    build: .
    container_name: vector-alice-cloud
    restart: always
    ports:
    - "3000:3000"
    env_file:
      - .env  # <--- Добавляем эту строку
    environment:
      - NODE_ENV=${NODE_ENV}
      - MQTT_HOST=${MQTT_HOST}
    depends_on:
      - mqtt-broker

  mqtt-broker:
    image: eclipse-mosquitto:latest
    container_name: vector-mqtt-broker
    restart: always
    ports:
    - "1883:1883"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log