version: '3.8'
services:
  vector-cloud:
    build: .
    container_name: vector-alice-cloud
    restart: always
    ports:
      - "3000:3000"
    # МЫ УБРАЛИ VOLUMES ОТСЮДА, чтобы не было ошибки монтажа
    environment:
      - NODE_ENV=production